### ISSUE TITLE
why is there still .tar.gz is inside the iso

### ISSUE THREAD

**Issue by candrapersada** [ventoy/vtoyboot#13]
why still use .tar.gz in the iso?

**Comment by ventoy** [comment]
iso is a read only file system.
In the vtoyboot.sh script, some temporary  process(e.g. chmod, create temp file or log) need the write permission.

So if the files are directly in the iso, user may run vtoyboot.sh directly under the mount path and this will cause some problem.

**Comment by candrapersada** [comment]
i mean without .tar.gz like this
[vtoyboot-1.0.15.iso](https://1drv.ms/u/s!AsI3GLV9fEYlilirTPhc7UgqLht6?e=BbtOIy)

**Comment by ventoy** [comment]
I understand.
As I said, when such ISO file connected to the VM, many distros will auto mount it to for example  /run/media/Vtoyboot.
Ok, now some user will open the terminal directly under /run/media/Vtoyboot/vtoyboot-1.0.15  and run `sudo sh vtoyboot.sh` here.

But vtoyboot.sh will generate some temporary file (e.g. logs) in the current directory. So if will fail to create such temporary files under /run/media/Vtoyboot/vtoyboot-1.0.15, because this is the mountpoint of the ISO file and is read-only.

User must copy the whole directory from the ISO file to the local path and run vtoyboot.sh there. But they may  not be aware of such restriction.
So I put vtoyboot.tar.gz inside the ISO file, user will have no choice but only can extract it to the local path, then it will OK.

**Comment by candrapersada** [comment]
i mean no need .tar.gz in iso
![Capture33](https://user-images.githubusercontent.com/36833664/125148998-702c6600-e160-11eb-9250-f2310d04d6c2.PNG)

**Comment by candrapersada** [comment]
iso without .tar.gz
![gambar](https://user-images.githubusercontent.com/36833664/125149177-a1f1fc80-e161-11eb-8090-a5508d313fd8.png)
![gambar](https://user-images.githubusercontent.com/36833664/125149208-c057f800-e161-11eb-81aa-21c0f536f61a.png)

**Comment by ventoy** [comment]
Didn't you understand what I said?

If I use an iso with out .tar.gz, people will run vtoyboot.sh directly under the ISO montpoint path, this will cause problem.
If so, I  will need to explain for all the users that, you can not run vtoyboot.sh directly under the ISO mount point path,
you must:
```
cp -a /run/media/vtoyboot-1.0.15   /home
cd /home/vtoyboot-1.0.15
sudo sh vtoyboot.sh
```

I don't want to do that.

**Comment by ventoy** [comment]
That is to say, when you connect the ISO file to the VM the ISO file,  `/dev/sr0` may be corresponding to the ISO file in the VM.
So:
```
mount /dev/sr0  /mnt
cd /mnt/vtoyboot-1.0.15
sudo sh vtoyboot.sh     <------ This will cause problem, because  /mnt/vtoyboot-1.0.15  is readonly
```


So user must do as follows:
```
mount /dev/sr0  /mnt
cp -a /mnt/vtoyboot-1.0.15  /home
cd /home/vtoyboot-1.0.15
sudo sh vtoyboot.sh
```

**Comment by candrapersada** [comment]
but on https://www.ventoy.net/en/plugin_vtoyboot.html there is only this information?
![gambar](https://user-images.githubusercontent.com/36833664/125149814-6fe29980-e165-11eb-9d36-33c67f2b2c2d.png)

**Comment by ventoy** [comment]
This page has not been updated.  I will update it soon.

**Comment by ventoy** [comment]
Even this page not updated, people will be not very confused. Because they will get the .tar.gz file from the iso and decompress it.
Or they will not find the vtoyboot.sh .

**Comment by ventoy** [comment]
I wrapper the .tar.gz into an ISO file only for convenience to upload the .tar.gz file into the VM.

**Comment by anwar-alsilwy** [comment]
Thanks for making vtoyboot.tar.gz inside .iso file.
now it's easier to mount it via Virtualbox instead of copy tar.gz file to usb drive then mount it to Virtualbox.
